Parcel insertion
chernyshewww/console-parcels pull request #1
Opened 2024-12-14 22:10 UTC by chernyshewww

2024-12-17 16:16 UTC, Fixey approved these changes

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/model/enums/StrategyType.java
> +    ONE_TO_ONE;
Лишняя ;

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/service/FileParserService.java
> +    // PROGRAM WILL SKIP ALL THE INVALID SEQUENCES AND WRITE WARNING ABOUT IT
Вроде комментарии убирал

2024-12-17 16:16 UTC, Fixey commented on src/test/java/FileParserServiceTests.java
> +package org.example;
Название пакета не корректное

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/strategy/StrategySelector.java
> +            default -> throw new IllegalArgumentException("Invalid strategy type: " + strategyType);
Зачем тебе default если у тебя енамы. Если что-то не используется - убирай

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/Main.java
> +            logger.debug("Reading parcels from file: {}", fileName);
Зачем тебе столько избыточного логирования. Причем внутри методов, когда они используются тоже логируется.

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/strategy/MaximumCapacityStrategy.java
> +
В начале Публичные метод потом приватные

2024-12-17 16:16 UTC, Fixey commented on build.gradle.kts
> +    implementation("ch.qos.logback:logback-classic:1.4.5")
Вначале имплементация потом тестовая имплементация

2024-12-17 16:16 UTC, Fixey commented on src/test/java/TruckTests.java
> +package org.example;
Не правильный пакет

2024-12-17 16:16 UTC, Fixey commented on src/main/java/com/deliverysystem/Main.java
> +            String fileName = "src/main/resources/parcels.txt";
Вынеси в константу

2024-12-17 16:16 UTC, Fixey commented on src/test/java/TruckTests.java
> +        // Arrange
Комментарии убери

2024-12-17 16:16 UTC, Fixey commented on src/test/java/FileParserServiceTests.java
> +        // Arrange
Комментарии убери

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +        // Arrange
Комментарии убери

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +package org.example;
Пакет поправь

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +        trucks.get(0).printTruck(1);
Тесты должны проверять без участия человека. А тут ты просишь распечать, проверок нет

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +        truck.printTruck(1);
тут нет проверки, зачем печатать?

2024-12-17 16:16 UTC, Fixey commented on src/test/java/FileParserServiceTests.java
> +
Структура файлов теста должна соответсвтовать структре проверяемых классов (в той же папочке и на том же месте)

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +
Структура файлов теста должна соответсвтовать структре проверяемых классов (в той же папочке и на том же месте)

2024-12-17 16:16 UTC, Fixey commented on src/test/java/MaximumCapacityStrategyTests.java
> +class MaximumCapacityStrategyTests {
Структура файлов теста должна соответсвтовать структре проверяемых классов (в той же папочке и на том же месте)

2024-12-17 16:23 UTC, chernyshewww commented on src/main/java/com/deliverysystem/Main.java
> +            logger.debug("Reading parcels from file: {}", fileName);
Следую вот этой постановке
![image](https://github.com/user-attachments/assets/b4e30258-928e-40e5-969c-0dd1728ed3cc)

2024-12-18 08:42 UTC, Fixey requested changes

2024-12-18 08:42 UTC, Fixey commented on src/main/java/com/deliverysystem/Main.java
> +            for (int i = 0; i < trucks.size(); i++) {
Дублить код не оч хорошо, можно вынести в метод

2024-12-18 08:42 UTC, Fixey commented on src/main/java/com/deliverysystem/service/ParcelLoaderService.java
> +    public List<TruckService> loadParcels(List<char[][]> parcels, StrategyType strategyType) {
Возвращаются не сервисы а сущности. Отедли сервис от сущности

2024-12-18 08:42 UTC, Fixey commented on src/main/java/com/deliverysystem/strategy/MaximumCapacityStrategy.java
> +    public List<TruckService> loadParcels(List<char[][]> parcels) {
Возвращаются не сервисы а сущности. Отедли сервис от сущности

2024-12-18 10:33 UTC, Fixey requested changes

2024-12-18 10:33 UTC, Fixey commented on src/main/java/com/deliverysystem/util/Constants.java
> +public class Constants {
Это не утильный класс, это должно быть в сущнсоти

2024-12-18 10:33 UTC, Fixey commented on src/main/java/com/deliverysystem/util/Constants.java
> +    public static final char EMPTY_CELL = ' ';
Это тоже закинь в сервис и в сущность

2024-12-18 10:33 UTC, Fixey commented on src/main/java/com/deliverysystem/model/enums/StrategyType.java
> +public enum StrategyType {
выкинь енамы на уровень выше

2024-12-18 10:43 UTC, Fixey approved these changes

2024-12-18 10:44 UTC, merged